version: '2'
services:
  humhub:
      image: snowping/humhub.docker:v1.2.0
      tty: true
      stdin_open: true
      links:
          - db
      volumes:
        - ${humhub_uploads}:/app/humhub/uploads
        - ${humhub_protected_runtime}:/app/humhub/protected/runtime
        - ${humhub_protected_config}:/app/humhub/protected/config
        - ${humhub_protected_modules}:/app/humhub/protected/modules
        - ${humhub_protected_themes}:/app/humhub/protected/themes
      volume_driver: ${volume_driver}
  db:
      image: mariadb
      tty: true
      stdin_open: true
      environment:
          - MYSQL_ROOT_PASSWORD=${db_root_password}
          - MYSQL_USER=${db_username}
          - MYSQL_PASSWORD=${db_password}
          - MYSQL_DATABASE=${db_name}
      volumes:
          - /var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      tty: true
      stdin_open: true
      links:
          - db:db
      environment:
          - MYSQL_ROOT_PASSWORD=${db_root_password}
          - MYSQL_USER=${db_username}
          - MYSQL_PASSWORD=${db_password}
  sftp:
      image: atmoz/sftp
      tty: true
      stdin_open: true
      volumes:
        - ${humhub_uploads}:/home/${humhub_sftp_username}/uploads
        - ${humhub_protected_runtime}:/home/${humhub_sftp_username}/protected/runtime
        - ${humhub_protected_config}:/home/${humhub_sftp_username}/protected/config
        - ${humhub_protected_modules}:/home/${humhub_sftp_username}/protected/modules
        - ${humhub_protected_themes}:/home/${humhub_sftp_username}/protected/themes
      volume_driver: ${volume_driver}
      command: ${humhub_sftp_username}:${humhub_sftp_password}:100:101
